# Generated by Django 4.2.3 on 2023-07-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_school_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Marklist',
        ),
    ]
