# Generated by Django 4.2.3 on 2023-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_school_marklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marklist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
